name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "BP123"
        pwd
        cd src
        docker build . --file Dockerfile --tag rubber-nugget:$(date +%s)
